### ISSUE TITLE
Connecting screen immediately exits without waiting for opponent

### ISSUE THREAD

**Issue by jimu** [averycrespi/thinktank#30]
### Steps to reproduce
1. visit https://thinktank.crespi.dev
2. click [Create Private Match]

This screen flashes on screen for a fraction of a second:

![screenshot](https://i.imgur.com/h3MN7v4.png)

Then the game starts without waiting for an opponent

### System:
* Google Chrome is up to date.  Version 85.0.4183.121 (Official Build) (64-bit)
* Windows 10 Pro 1909 18363.959

Same behavior using alternate browser through different IP
* Tor Browser 10.0 (based on Mozilla Firefox 78.3.0esr) (64-bit)

**Comment by averycrespi** [comment]
Thanks for the report!

For now, those are both intended behaviors - although I may tweak the UX in the future.

Other games like [Camelot](https://www.playcamelot.com/play/owwSwagBp/white) follow the same general pattern.

**Comment by jimu** [comment]
I feel the UX in Camelot and Thinktank differ significantly.

Camelot flashes the invite URL momentarily and replaces it with the game board overlaid with a model dialog instructing the user to share the link to proceed:

![Camelot screenshot](https://i.imgur.com/IuUQnMP.png)

Thinktank flashes the invite URL momentarily and replaces it with a running game:

![Thinktank screenshot](https://i.imgur.com/AYexDaa.png)

Thinktank hides the invite step entirely off the screen.

Thinktank is perfectly sized for 1080p resolution. Because it it makes perfect use of the screen real estate; it appears to
a traditionally designed game interface. This makes the need to scroll even less obvious.

The user knows a share like was offered a moment ago, but it's gone now (which is strange), and the game has already
started without a second player (which is also strange). Honestly, I assumed the game was bugged, broken, and abandoned like so many other projects on the Internet. 

You've done a really nice job with the minimalist theme, by the way.

**Comment by averycrespi** [comment]
Ah - good point about the invite step being off-screen!

I can definitely flash the invite URL at the start of the game.

**Comment by averycrespi** [comment]
Preliminary design for the modal:
![Screenshot_20201005_105520](https://user-images.githubusercontent.com/9702999/95114958-93ba1000-06f9-11eb-8748-964520ce148b.png)

**Comment by jimu** [comment]
This doesn't give the user clear guidance on what to do after sharing the link.

I have the following questions when I see the above screen:

* Do I need to press `DISMISS` to begin playing the game?
* Will pressing `DISMISS` cancel the game?
* Am I supposed to just wait until the other player joins?

I think this is how most players have come to expect a multiplayer game to begin:

![Wait or cancel screenshot](https://i.imgur.com/S0EgkiE.gif)

So I kind-of expect the `DISMISS` button will cancel the game, but I'm not sure and that makes me anxious.
